### PR TITLE
USNP 8 Randomized Assignments

### PR DESCRIPTION
**Pull request by RubySpeeders**
As a user, I want to click the assign button and get randomized assignments. 

**A/C**
- after selecting musicians and instruments and clicking the assignments button, users are brought to a new page with randomized assignments
- assignments are random

in this ticket, I also added an interfaces and types folder for cleaner code.

**Screen Recording**

### CODE REVIEW

**Comment by RubySpeeders** [comment]
@cheesehero112 ready for review if you want to take a look! I went out of scope and added a types and interfaces folder. I think it will help clean up the code.

**Comment by cheesehero112** [comment]
@RubySpeeders Random assignments work! It's great that if I select 5 musicians but only 3 instruments, I can't click the assignment button. Eventually, we can add a toast or warning message to let the user know to select the same number of instruments in order to click the assignments. 

Can we ask the percussionists if they ever double instruments? i.e. - there are 3 players, and 2 of them play snare drum and one play the bass drum? If so, we will need to come up with a different way to select instruments.

**Review by cheesehero112 — APPROVED** [review]
Looks good!

@RubySpeeders Random assignments work! It's great that if I select 5 musicians but only 3 instruments, I can't click the assignment button. Eventually, we can add a toast or warning message to let the user know to select the same number of instruments in order to click the assignments.

Can we ask the percussionists if they ever double instruments? i.e. - there are 3 players, and 2 of them play snare drum and one play the bass drum? If so, we will need to come up with a different way to select instruments.

**Comment by charlottekies** [comment]
> Can we ask the percussionists if they ever double instruments? i.e. - there are 3 players, and 2 of them play snare drum and one play the bass drum? If so, we will need to come up with a different way to select instruments.

@RubySpeeders @cheesehero112 I texted Chad to ask -- I'll get an answer back soon and will let you know what I find out

**Review by charlottekies — COMMENTED** [review]
I like the interfaces directory. 

My gut feeling says for the purposes of funerals, there won't be two snares or two tenors or two base drums. I think we should probably confirm before merging though. Perhaps we can, at the same time, get a list of the type of ceremonies this randomizer is needed for as well. I'll include that in my research aka bothering of chad. Will approve or comment again when I know more

**Comment by RubySpeeders** [comment]
I will add an issue to the backlog re: two snares or two of any instrument; I feel that V1 can be deployed without that feature. If it becomes necessary, then we can work on a solution!

**Pull request merged**
