### PR TITLE
USNP11 Vertical Layout 

### PR DESCRIPTION
**Pull request by RubySpeeders**
changing the layout to have the musicians and instruments side-by-side

### CODE REVIEW

**Comment by RubySpeeders** [comment]
Screenshot 2023-06-19 at 10 21 22 AM

@charlottekies @cheesehero112 Disregarding the instruments panel (I think @cheesehero112 is working with the instrument images so I don't want to mess with it and create merge conflicts!), I know on the figma [,](https://www.figma.com/file/wSCqjCFyPt1AeVAZsVcvRv/Band-Assignment-App?type=design&node-id=0%3A1&t=UhLSdSYypCE5WAvn-1) we have 4 musicians across, but I think on the actual screen it kind of looks good as three across so it is a nice "square" of images. What do you think? President's Own is 12 drummers so it will also be a "square" of images.

**Comment by cheesehero112** [comment]
@RubySpeeders It looks good to me! We will need to make the page responsive anyways with some rules (i.e. - min/ max width of each section), so perhaps we can set this 3 x 3 player view as a default.

**Review by charlottekies — CHANGES_REQUESTED** [review]
Ah do you have a screen shot to share on the PR?

**Review by charlottekies — COMMENTED** [review]
@RubySpeeders What do the images look like on a mobile device? I think I like the square, and the side-by-side approach on desktop. Keeping a mobile-first design in mind, I'm curious to know if this will change the mobile layout.

**Comment by RubySpeeders** [comment]
@charlottekies Here is how it would look on an iphone:

https://github.com/RubySpeeders/US-Navy-Project/assets/69406113/1188b1e5-8d91-4e02-8a01-5fe9bb28c808

**Pull request merged**
